dist: xenial
language: python

addons:
  apt:
    packages:
    - libsane-dev

# No tests: just check it can build and install
script:
 - python setup.py build
 - python setup.py install

after_script:
 - pip install pycodestyle pyflakes
 - pycodestyle --statistics --count .
 - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
  include:
    - python: pypy2.7-6.0
    - python: pypy3.5-6.0
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7